"use client"

import { useEffect, useState } from 'react';
import { ShieldCheck, Stethoscope, CheckCircle2, TriangleAlert, PhoneCall } from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';

const DISCLAIMER_KEY = 'myreportbuddy_disclaimer_accepted';

const disclaimerPoints = [
  {
    heading: 'Not a Medical Device',
    body: 'MyReportBuddy is not a medical device and has not been registered or approved by the Central Drugs Standard Control Organisation (CDSCO) under the Medical Devices Rules, 2017. It does not provide medical advice, clinical diagnosis, prognosis, or treatment recommendations.',
  },
  {
    heading: 'Informational Purpose Only',
    body: 'All AI-generated analysis is provided for general informational and educational purposes only. Outputs may be incomplete, inaccurate, or not applicable to your specific medical circumstances, history, medications, or comorbidities.',
  },
  {
    heading: 'Consult a Qualified Medical Practitioner',
    body: 'You must consult a medical practitioner registered under the National Medical Commission Act, 2019, or a qualified specialist before making any decision regarding your health, diagnosis, or treatment. Do not disregard professional medical advice or delay seeking it on the basis of anything generated by this Service.',
  },
  {
    heading: 'No Liability for Reliance',
    body: 'MyReportBuddy and its operators expressly disclaim all liability for any loss, injury, or harm arising from your reliance on AI-generated analysis. Use of this Service constitutes your acknowledgement that such reliance is entirely at your own risk.',
  },
  {
    heading: 'Medical Emergency',
    body: 'If you are experiencing a medical emergency, do not use this Service. Call the National Emergency Number 112 or your nearest emergency services immediately.',
  },
];

export default function DisclaimerModal() {
  const [open, setOpen] = useState(false);

  useEffect(() => {
    const accepted = localStorage.getItem(DISCLAIMER_KEY);
    if (!accepted) setOpen(true);
  }, []);

  const handleAccept = () => {
    localStorage.setItem(DISCLAIMER_KEY, 'true');
    setOpen(false);
  };

  return (
    <Dialog open={open} onOpenChange={() => {}}>
      <DialogContent
        className="sm:max-w-lg p-0 gap-0 overflow-hidden rounded-2xl border-0 shadow-2xl"
        onPointerDownOutside={(e) => e.preventDefault()}
        onEscapeKeyDown={(e) => e.preventDefault()}
        aria-describedby="disclaimer-description"
      >
        {/* Gradient header */}
        <div className="bg-gradient-to-br from-amber-500 to-orange-500 px-6 py-5 flex items-center gap-3">
          <div className="h-11 w-11 rounded-xl bg-white/20 flex items-center justify-center shrink-0">
            <Stethoscope className="h-6 w-6 text-white" aria-hidden="true" />
          </div>
          <div>
            <DialogHeader>
              <DialogTitle className="text-white font-extrabold text-lg leading-tight">
                Medical Information Disclaimer
              </DialogTitle>
            </DialogHeader>
            <p className="text-amber-100 text-xs mt-0.5 font-medium">
              Please read carefully before using this Service
            </p>
          </div>
        </div>

        {/* Body */}
        <div className="px-6 py-5 space-y-4 max-h-[60vh] overflow-y-auto">
          <DialogDescription id="disclaimer-description" className="text-left space-y-4">

            {/* Intro */}
            <p className="text-sm text-slate-600 dark:text-slate-300 leading-relaxed">
              This Service uses artificial intelligence to assist in interpreting medical
              reports. By proceeding, you acknowledge and agree to the following terms:
            </p>

            {/* Disclaimer points */}
            <ul className="space-y-3">
              {disclaimerPoints.map(({ heading, body }) => (
                <li key={heading} className="flex items-start gap-3 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                  {heading === 'Medical Emergency'
                    ? <PhoneCall className="h-4 w-4 text-red-500 shrink-0 mt-0.5" aria-hidden="true" />
                    : <TriangleAlert className="h-4 w-4 text-amber-500 shrink-0 mt-0.5" aria-hidden="true" />
                  }
                  <span>
                    <strong className="text-slate-800 dark:text-slate-200">{heading}: </strong>
                    {body}
                  </span>
                </li>
              ))}
            </ul>

            {/* Security note */}
            <div className="flex items-start gap-3 bg-emerald-50 dark:bg-emerald-950/20 border border-emerald-200 dark:border-emerald-800 rounded-xl px-4 py-3 text-sm text-emerald-800 dark:text-emerald-300">
              <ShieldCheck className="h-5 w-5 mt-0.5 shrink-0 text-emerald-600 dark:text-emerald-400" aria-hidden="true" />
              <p>
                <strong>Data Privacy:</strong> Uploaded files are processed securely and are
                not permanently stored on our servers. Your data is handled in accordance
                with our{' '}
                <a
                  href="/privacy"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline underline-offset-2 hover:text-emerald-600 dark:hover:text-emerald-200 transition-colors"
                >
                  Privacy Policy
                </a>{' '}
                and applicable Indian law, including the Digital Personal Data Protection
                Act, 2023.
              </p>
            </div>

            {/* Acknowledgement statement */}
            <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed border-t border-slate-100 dark:border-slate-800 pt-3">
              By clicking <em>&ldquo;I Acknowledge &amp; Accept&rdquo;</em> below, you confirm that you
              have read, understood, and agree to this disclaimer and our{' '}
              <a href="/privacy" target="_blank" rel="noopener noreferrer" className="underline underline-offset-2 hover:text-slate-700 dark:hover:text-slate-300 transition-colors">
                Privacy Policy
              </a>.
              You further confirm that you are at least 18 years of age or are using this
              Service under the supervision of a parent or lawful guardian.
            </p>

          </DialogDescription>
        </div>

        {/* Footer */}
        <DialogFooter className="px-6 pb-6 pt-2">
          <Button
            onClick={handleAccept}
            className="w-full rounded-xl font-semibold h-11 gap-2"
            aria-label="Acknowledge and accept the medical disclaimer"
          >
            <CheckCircle2 className="h-4 w-4" aria-hidden="true" />
            I Acknowledge &amp; Accept
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
